<%@ taglib prefix="s" uri="/struts-tags" %>
<%  response.setHeader("Expires", "0");response.setHeader("Cache-Control", "must-revalidate, post-check=0, pre-check=0");response.setHeader("Pragma", "public");
response.setHeader("Content-Disposition","inline; filename=excavations.csv");response.setContentType("application/csv"); %>ID,Company Name,Company Contact,Cut Description,Cut Type,Permit Number,Start Date,Address,Depth,Width,Length,Status,Utility,Cut Latitude,Cut Longitude
<s:iterator var="one" value="cuts"><s:property value="id" />,"<s:property value="permit.company" />","<s:property value="permit.contact" />","<s:property value="cut_description" />",<s:property value="cut_type" />,<s:property value="permit_num" />,<s:property value="permit.start_date" />,"<s:property value="address" />",<s:property value="depth" />,<s:property value="width" />,<s:property value="length" />,<s:property value="status" />,<s:property value="utility_type" />,<s:property value="address.loc_lat" />,<s:property value="address.loc_long" />
</s:iterator>























































